@remoteUrl = https://lab-track-system.onrender.com
@localUrl=http://localhost:4000
@baseUrl = {{localUrl}}
# @baseUrl = {{localUrl}}

@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFydW4iLCJwYXNzd29yZCI6ImFydW5wYXNzIiwiaWF0IjoxNjg1MjE2OTE0LCJleHAiOjE2ODUzMDMzMTR9.4uOTk-EBMAdbhldrZyepiIdQfRDRr1amOnNwAxuPbUg
@superUserToken =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN1cGVyIiwicGFzc3dvcmQiOiJwYXNzIiwiaWF0IjoxNjk4NjQ2ODk1LCJleHAiOjE2OTg3MzMyOTV9.s8Pic97WQBDxpl9isoSKGMcvxnG9oOdIpf2k0j4KF04
###

#### LOGIN AND SIGNUP

POST  {{baseUrl}}/login
Content-Type: application/json

{
  "username":"super",
  "password":"pass"
}

#### USERS

### GET all users

GET {{baseUrl}}/users
Content-Type: application/json
x-access-token: {{superUserToken}}

{
  "role":"USER"
}

### TESTS

### Get tests

GET {{baseUrl}}/tests
Content-Type: application/json
x-access-token: {{superUserToken}}


### Create a Test


POST {{baseUrl}}/tests/create
Content-Type: application/json
x-access-token: {{superUserToken}}

{
  "name": "RBC Count 4",
  "description": "Red Blood Cells Count 4",
  "resultType": "VALUE",
  "unit":"10^12/L",
  "minRange": null,
  "maxRange": null,
  "pregnancyMinRange": null,
  "pregnancyMaxRange": null,
  "femaleMinRange":4.5,
  "femaleMaxRange":5,
  "maleMinRange":4.7,
  "maleMaxRange":6.2,
  "childMinRange":3.5,
  "childMaxRange":5.5,
  "newBornMinRange":4.8,
  "newBornMaxRange":7.1,
  "newBornMaxAgeMonths":4,
  "childMaxAge":12,
  "resultStrings": null,
  "createdBy": "super"
}

### TEST GROUPS

### Get test groups

GET {{baseUrl}}/testgroups
Content-Type: application/json
x-access-token: {{superUserToken}}

### POST test groups

POST {{baseUrl}}/testgroups/create
Content-Type: application/json
x-access-token: {{superUserToken}}

{
  "name": "Lipid Profile 3",
  "description": "Lipid profile group 3",
  "testIds": ["6478ab27f48020c613ab3acc","6477b41332ade7e70fdcc849","6477c4bd20aad115f7c6f443"]
}


### DELETE test groups

DELETE {{baseUrl}}/testgroups/651236125130e2d9a6153c09
Content-Type: application/json
x-access-token: {{superUserToken}}


### ACTIVITIES

### Get Activities

GET {{baseUrl}}/activities
Content-Type: application/json
x-access-token: {{superUserToken}}

## Create

POST {{baseUrl}}/activities/create
Content-Type: application/json
x-access-token: {{superUserToken}}

{
  "activityName": "Lipid Profile 3",
  "activityDescription": "Lipid profile group 3",
  "active": true
}