@remoteUrl = https://lab-track-system.onrender.com
@localUrl=http://localhost:4000
@baseUrl = {{remoteUrl}}
# @baseUrl = {{localUrl}}

@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFydW4iLCJwYXNzd29yZCI6ImFydW5wYXNzIiwiaWF0IjoxNjg1MjE2OTE0LCJleHAiOjE2ODUzMDMzMTR9.4uOTk-EBMAdbhldrZyepiIdQfRDRr1amOnNwAxuPbUg
@superUserToken =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN1cGVyIiwicGFzc3dvcmQiOiJwYXNzIiwiaWF0IjoxNjg1NTY3MTA4LCJleHAiOjE2ODU2NTM1MDh9.st6MGt-DqCU65piqbkrhHjo9qSTt4majvAVgWVTwrNI
###

#### LOGIN AND SIGNUP

POST  {{baseUrl}}/login
Content-Type: application/json

{
  "username":"super",
  "password":"pass"
}

#### USERS

### GET all users

GET {{baseUrl}}/users
Content-Type: application/json
x-access-token: {{superUserToken}}

{
  "role":"USER"
}

### TESTS

### Get tests

GET {{baseUrl}}/tests
Content-Type: application/json
x-access-token: {{superUserToken}}


### Create a Test


POST {{baseUrl}}/tests/create
Content-Type: application/json
x-access-token: {{superUserToken}}

{
  "name": "RBC Count 4",
  "description": "Red Blood Cells Count 4",
  "resultType": "VALUE",
  "unit":"10^12/L",
  "minRange": null,
  "maxRange": null,
  "pregnancyMinRange": null,
  "pregnancyMaxRange": null,
  "femaleMinRange":4.5,
  "femaleMaxRange":5,
  "maleMinRange":4.7,
  "maleMaxRange":6.2,
  "childMinRange":3.5,
  "childMaxRange":5.5,
  "newBornMinRange":4.8,
  "newBornMaxRange":7.1,
  "newBornMaxAgeMonths":4,
  "childMaxAge":12,
  "resultStrings": null,
  "createdBy": "super"
}